/*
   3D model generated by Jo Map Editor v6.1
*/

#ifndef __3D_MODELA_H__
# define __3D_MODELA_H__

static POINT    PointA[] =
{
	{3631363, -4389748, 33977},
	{5758317, -4389748, 33977},
	{4694840, -4043718, 33977},
	{4427015, -2262795, 33977},
	{4962666, -2262795, 33977},
	{4694841, -2219840, 33977},
	{4029189, -3326271, 33977},
	{5360492, -3326271, 33977},
	{4694840, -3131778, 33977},
};

static POLYGON    PolygonA[] =
{
	{{0, 0, 65536}, {8, 7, 4, 5}},
	{{0, 0, 65536}, {6, 8, 5, 3}},
	{{0, 0, 65536}, {0, 2, 8, 6}},
	{{0, 0, 65536}, {2, 1, 7, 8}},
};

static ATTR    AttributeA[] =
{
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
};

jo_3d_mesh    MeshA =
{
	.data =
	{
		PointA,
		9,
		PolygonA,
		4,
		AttributeA
	}
};

/* Call this function in you code to display all objects */
static __jo_force_inline void       display_a_mesh(void)
{
	jo_3d_mesh_draw(&MeshA);
}

#endif /* !__3D_MODELA_H__ */
