/*
   3D model generated by Jo Map Editor v6.1
*/

#ifndef __3D_MODELB_H__
# define __3D_MODELB_H__

static POINT    PointB[] =
{
	{3323641, -4316439, 42450},
	{2294079, -4316439, 42450},
	{3323641, -2215204, 42450},
	{2294079, -2215204, 42450},
	{3400952, -2740513, 42450},
	{3400952, -3265821, 42450},
	{3400952, -3791130, 42450},
	{1927346, -3791130, 42450},
	{2294079, -3265822, 42450},
	{1927346, -2740513, 42450},
};

static POLYGON    PolygonB[] =
{
	{{0, 0, -65536}, {4, 9, 3, 2}},
	{{0, 0, -65536}, {0, 1, 7, 6}},
	{{0, 0, -65536}, {6, 7, 8, 5}},
	{{0, 0, -65536}, {5, 8, 9, 4}},
};

static ATTR    AttributeB[] =
{
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
};

jo_3d_mesh    MeshB =
{
	.data =
	{
		PointB,
		10,
		PolygonB,
		4,
		AttributeB
	}
};

/* Call this function in you code to display all objects */
static __jo_force_inline void       display_b_mesh(void)
{
	jo_3d_mesh_draw(&MeshB);
}

#endif /* !__3D_MODELB_H__ */
