/*
   3D model generated by Jo Map Editor v6.1
*/

#ifndef __3D_MODELC_H__
# define __3D_MODELC_H__

static POINT    PointC[] =
{
	{-3687778, -2715969, 1},
	{-3248874, -2861670, 1},
	{-3103172, -3175616, 1},
	{-3248874, -3489560, 1},
	{-3687778, -3635262, 1},
	{-3971089, -1886173, 1},
	{-2904995, -2056763, 1},
	{-2438930, -2522832, 1},
	{-2268336, -3159491, 1},
	{-2438930, -3796152, 1},
	{-2904995, -4262220, 1},
	{-3971089, -4432810, 1},
};

static POLYGON    PolygonC[] =
{
	{{0, 0, 65536}, {3, 4, 11, 10}},
	{{0, 0, 65536}, {2, 3, 9, 8}},
	{{0, 0, 65536}, {1, 7, 6, 6}},
	{{0, 0, 65536}, {3, 10, 9, 9}},
	{{0, 0, 65536}, {1, 2, 8, 7}},
	{{0, 0, 65536}, {0, 1, 6, 5}},
};

static ATTR    AttributeC[] =
{
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
};

jo_3d_mesh    MeshC =
{
	.data =
	{
		PointC,
		12,
		PolygonC,
		6,
		AttributeC
	}
};

/* Call this function in you code to display all objects */
static __jo_force_inline void       display_c_mesh(void)
{
	jo_3d_mesh_draw(&MeshC);
}

#endif /* !__3D_MODELC_H__ */
