/*
   3D model generated by Jo Map Editor v6.1
*/

#ifndef __3D_MODELDOWN_H__
# define __3D_MODELDOWN_H__

static POINT    PointDown[] =
{
	{1302075, -3874459, 47623},
	{684203, -5928433, 47623},
	{-1302074, -3874460, 47623},
	{-684201, -5928433, 47623},
	{684203, -5777933, 47623},
	{-684201, -5777933, 47623},
	{-693603, -5038694, 47623},
	{-879128, -4407677, 47623},
	{879129, -4407677, 47623},
	{693604, -5038694, 47623},
	{0, -3874460, 47623},
	{0, -6068967, 47623},
	{0, -5927032, 47623},
	{0, -4407677, 47623},
	{0, -5029772, 47623},
};

static POLYGON    PolygonDown[] =
{
	{{0, 0, 65536}, {12, 11, 1, 4}},
	{{0, 0, 65536}, {14, 12, 4, 9}},
	{{0, 0, 65536}, {2, 7, 13, 10}},
	{{0, 0, 65536}, {7, 6, 14, 13}},
	{{0, 0, 65536}, {13, 14, 9, 8}},
	{{0, 0, 65536}, {6, 5, 12, 14}},
	{{0, 0, 65536}, {5, 3, 11, 12}},
	{{0, 0, 65536}, {10, 13, 8, 0}},
};

static ATTR    AttributeDown[] =
{
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
};

jo_3d_mesh    MeshDown =
{
	.data =
	{
		PointDown,
		15,
		PolygonDown,
		8,
		AttributeDown
	}
};

/* Call this function in you code to display all objects */
static __jo_force_inline void       display_down_mesh(void)
{
	jo_3d_mesh_draw(&MeshDown);
}

#endif /* !__3D_MODELDOWN_H__ */
