/*
   3D model generated by Jo Map Editor v6.1
*/

#ifndef __3D_MODELLEFT_H__
# define __3D_MODELLEFT_H__

static POINT    PointLeft[] =
{
	{3874460, 1302075, 47623},
	{5928433, 684202, 47623},
	{3874460, -1302074, 47623},
	{5928433, -684201, 47623},
	{5777933, 684202, 47623},
	{5777933, -684201, 47623},
	{5038694, -693603, 47623},
	{4407677, -879128, 47623},
	{4407677, 879129, 47623},
	{5038694, 693604, 47623},
	{3874460, 0, 47623},
	{6068967, 0, 47623},
	{5927032, 0, 47623},
	{4407677, 0, 47623},
	{5029772, 0, 47623},
};

static POLYGON    PolygonLeft[] =
{
	{{0, 0, 65536}, {12, 11, 1, 4}},
	{{0, 0, 65536}, {14, 12, 4, 9}},
	{{0, 0, 65536}, {2, 7, 13, 10}},
	{{0, 0, 65536}, {7, 6, 14, 13}},
	{{0, 0, 65536}, {13, 14, 9, 8}},
	{{0, 0, 65536}, {6, 5, 12, 14}},
	{{0, 0, 65536}, {5, 3, 11, 12}},
	{{0, 0, 65536}, {10, 13, 8, 0}},
};

static ATTR    AttributeLeft[] =
{
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
};

jo_3d_mesh    MeshLeft =
{
	.data =
	{
		PointLeft,
		15,
		PolygonLeft,
		8,
		AttributeLeft
	}
};

/* Call this function in you code to display all objects */
static __jo_force_inline void       display_left_mesh(void)
{
	jo_3d_mesh_draw(&MeshLeft);
}

#endif /* !__3D_MODELLEFT_H__ */
