/*
   3D model generated by Jo Map Editor v6.1
*/

#ifndef __3D_MODELRIGHT_H__
# define __3D_MODELRIGHT_H__

static POINT    PointRight[] =
{
	{-3874460, -1283564, 47623},
	{-5928433, -665691, 47623},
	{-3874459, 1320585, 47623},
	{-5928432, 702713, 47623},
	{-5777934, -665691, 47623},
	{-5777933, 702713, 47623},
	{-5038693, 712114, 47623},
	{-4407677, 897639, 47623},
	{-4407678, -860618, 47623},
	{-5038694, -675093, 47623},
	{-3874460, 18510, 47623},
	{-6068967, 18511, 47623},
	{-5927032, 18511, 47623},
	{-4407677, 18510, 47623},
	{-5029772, 18510, 47623},
};

static POLYGON    PolygonRight[] =
{
	{{0, 0, 65536}, {12, 11, 1, 4}},
	{{0, 0, 65536}, {14, 12, 4, 9}},
	{{0, 0, 65536}, {2, 7, 13, 10}},
	{{0, 0, 65536}, {7, 6, 14, 13}},
	{{0, 0, 65536}, {13, 14, 9, 8}},
	{{0, 0, 65536}, {6, 5, 12, 14}},
	{{0, 0, 65536}, {5, 3, 11, 12}},
	{{0, 0, 65536}, {10, 13, 8, 0}},
};

static ATTR    AttributeRight[] =
{
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
};

jo_3d_mesh    MeshRight =
{
	.data =
	{
		PointRight,
		15,
		PolygonRight,
		8,
		AttributeRight
	}
};

/* Call this function in you code to display all objects */
static __jo_force_inline void       display_right_mesh(void)
{
	jo_3d_mesh_draw(&MeshRight);
}

#endif /* !__3D_MODELRIGHT_H__ */
