/*
   3D model generated by Jo Map Editor v6.1
*/

#ifndef __3D_MODELX_H__
# define __3D_MODELX_H__

static POINT    PointX[] =
{
	{3991554, 1986661, -115596},
	{4513827, 2508936, -115596},
	{2491083, 4531680, -115596},
	{1968809, 4009406, -115596},
	{1968809, 2508936, -115596},
	{2491083, 1986661, -115596},
	{4513827, 4009405, -115596},
	{3991554, 4531680, -115596},
	{3241318, 2755248, -115596},
	{2737396, 3259171, -115596},
	{3745241, 3259171, -115596},
	{3241318, 3763093, -115596},
};

static POLYGON    PolygonX[] =
{
	{{0, 0, 65536}, {9, 11, 2, 3}},
	{{0, 0, 65536}, {0, 1, 10, 8}},
	{{0, 0, 65536}, {8, 10, 11, 9}},
	{{0, 0, 65536}, {5, 8, 9, 4}},
	{{0, 0, 65536}, {10, 6, 7, 11}},
};

static ATTR    AttributeX[] =
{
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
};

jo_3d_mesh    MeshX =
{
	.data =
	{
		PointX,
		12,
		PolygonX,
		5,
		AttributeX
	}
};

/* Call this function in you code to display all objects */
static __jo_force_inline void       display_x_mesh(void)
{
	jo_3d_mesh_draw(&MeshX);
}

#endif /* !__3D_MODELX_H__ */
