/*
   3D model generated by Jo Map Editor v6.1
*/

#ifndef __3D_MODELY_H__
# define __3D_MODELY_H__

static POINT    PointY[] =
{
	{-3422725, 4555856, -1},
	{-3926407, 4064812, -1},
	{-1452172, 4064813, -1},
	{-1955853, 4555856, -1},
	{-3068853, 3299947, -1},
	{-2309726, 3299947, -1},
	{-2689290, 3825315, -1},
	{-3068853, 2118064, -1},
	{-2309726, 2118064, -1},
};

static POLYGON    PolygonY[] =
{
	{{0, 0, 65536}, {4, 6, 0, 1}},
	{{0, 0, 65536}, {4, 5, 6, 6}},
	{{0, 0, 65536}, {5, 2, 3, 6}},
	{{0, 0, 65536}, {5, 4, 7, 8}},
};

static ATTR    AttributeY[] =
{
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
};

jo_3d_mesh    MeshY =
{
	.data =
	{
		PointY,
		9,
		PolygonY,
		4,
		AttributeY
	}
};

/* Call this function in you code to display all objects */
static __jo_force_inline void       display_y_mesh(void)
{
	jo_3d_mesh_draw(&MeshY);
}

#endif /* !__3D_MODELY_H__ */
