/*
   3D model generated by Jo Map Editor v6.1
*/

#ifndef __3D_MODELZ_H__
# define __3D_MODELZ_H__

static POINT    PointZ[] =
{
	{-4091328, 2124200, -1},
	{-5578874, 2124200, -1},
	{-4091328, 4451676, -1},
	{-5665615, 4451676, -1},
	{-4029697, 3913937, -1},
	{-5417521, 3898634, -1},
	{-4091328, 3084372, -1},
	{-5665615, 2661940, -1},
	{-4283478, 2677243, -1},
	{-5665615, 3491504, -1},
	{-3923455, 2673884, -1},
	{-5758083, 3900527, -1},
};

static POLYGON    PolygonZ[] =
{
	{{0, 0, -65536}, {7, 8, 0, 1}},
	{{0, 0, -65536}, {6, 8, 9, 5}},
	{{0, 0, 65536}, {11, 9, 5, 3}},
	{{0, 0, 65536}, {4, 2, 3, 5}},
	{{0, 0, -65536}, {10, 0, 8, 6}},
};

static ATTR    AttributeZ[] =
{
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
	ATTRIBUTE(Dual_Plane, SORT_CEN, No_Texture, 0x801f, CL32KRGB | No_Gouraud, CL32KRGB | MESHoff, sprPolygon, UseLight),
};

jo_3d_mesh    MeshZ =
{
	.data =
	{
		PointZ,
		12,
		PolygonZ,
		5,
		AttributeZ
	}
};

/* Call this function in you code to display all objects */
static __jo_force_inline void       display_z_mesh(void)
{
	jo_3d_mesh_draw(&MeshZ);
}

#endif /* !__3D_MODELZ_H__ */
